export const products = [
  { id: '1', name: 'Apple', image: 'apple.jpeg' },
  { id: '2', name: 'Radish', image: 'radish.png' },
  { id: '3', name: 'Banana', image: 'banana.jpeg' },
  { id: '4', name: 'Onion', image: 'onion.jpeg' },
  { id: '5', name: 'Lettuce', image: 'lettuce.jpeg' },
  { id: '6', name: 'Pineapple', image: 'pineapple.jpeg' },
  { id: '7', name: 'Peanut', image: 'peanut.jpeg' },
  { id: '8', name: 'Raspberry', image: 'raspberry.jpeg' },
  { id: '9', name: 'Strawberry', image: 'strawberry.jpeg' },
  { id: '10', name: 'Blueberry', image: 'blueberry.jpeg' },
  { id: '11', name: 'Brokkoli', image: 'brokkoli.jpeg' },
  { id: '12', name: 'Cabbage', image: 'cabbage.jpeg' },
  { id: '13', name: 'Carrot', image: 'carrot.jpeg' },
  { id: '14', name: 'Fennel', image: 'fennel.jpeg' },
  { id: '15', name: 'Butternut Squash', image: 'butternut.jpeg' },
  { id: '16', name: 'Hokkaido', image: 'hokkaido.jpeg' },
  { id: '17', name: 'Mango', image: 'mango.jpeg' },
  { id: '18', name: 'Mushrooms', image: 'mushrooms.jpeg' },
  { id: '19', name: 'Papaya', image: 'papaya.jpeg' },
  { id: '20', name: 'Peach', image: 'peach.jpeg' },
  { id: '21', name: 'Pear', image: 'pear.jpeg' },
  { id: '22', name: 'Potato', image: 'potato.jpeg' },
  { id: '23', name: 'Radicchio', image: 'radicchio.jpeg' },
  { id: '24', name: 'Tomato', image: 'tomato.jpeg' },
];
